# Generated by Django 4.2.6 on 2023-10-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_supplier_options_alter_purchasebilldetails_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='total',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salebilldetails',
            name='total',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
