# Generated by Django 4.2.6 on 2023-11-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_purchasebilldetails_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebill',
            name='email',
        ),
        migrations.AddField(
            model_name='supplier',
            name='gender',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=2),
        ),
        migrations.AlterField(
            model_name='salebill',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salebill',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='salebill',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
