# Generated by Django 4.2.6 on 2023-11-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_salebill_email_supplier_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='gender',
            field=models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], default='Laki-laki', max_length=12),
        ),
    ]
