# Generated by Django 4.2.6 on 2023-11-03 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_supplier_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasebilldetails',
            old_name='tcs',
            new_name='debt',
        ),
        migrations.RenameField(
            model_name='purchasebilldetails',
            old_name='destination',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='purchasebilldetails',
            old_name='veh',
            new_name='pph',
        ),
        migrations.RenameField(
            model_name='purchasebilldetails',
            old_name='eway',
            new_name='ppn',
        ),
        migrations.RenameField(
            model_name='purchasebilldetails',
            old_name='cess',
            new_name='retur',
        ),
        migrations.RenameField(
            model_name='purchasebilldetails',
            old_name='po',
            new_name='stat',
        ),
        migrations.RenameField(
            model_name='salebill',
            old_name='gstin',
            new_name='npwp',
        ),
        migrations.RenameField(
            model_name='salebilldetails',
            old_name='tcs',
            new_name='debt',
        ),
        migrations.RenameField(
            model_name='salebilldetails',
            old_name='destination',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='salebilldetails',
            old_name='veh',
            new_name='pph',
        ),
        migrations.RenameField(
            model_name='salebilldetails',
            old_name='eway',
            new_name='ppn',
        ),
        migrations.RenameField(
            model_name='salebilldetails',
            old_name='cess',
            new_name='retur',
        ),
        migrations.RenameField(
            model_name='salebilldetails',
            old_name='po',
            new_name='stat',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='gstin',
            new_name='npwp',
        ),
    ]
