# Generated by Django 4.2.6 on 2023-11-03 04:34

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_rename_tcs_purchasebilldetails_debt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], default='Laki-laki', max_length=12)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('npwp', models.CharField(max_length=15, unique=True)),
                ('t_debt', models.CharField(blank=True, max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='grade',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='grade',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
