# Generated by Django 4.2.6 on 2023-11-12 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_salebill_address_remove_salebill_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='grade',
        ),
        migrations.CreateModel(
            name='SupDebtHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('total', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('remain', models.IntegerField(default=0)),
                ('retur', models.IntegerField(default=0)),
                ('stat', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtsupplier', to='transactions.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='CusDebtHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('total', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('remain', models.IntegerField(default=0)),
                ('retur', models.IntegerField(default=0)),
                ('stat', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtcustomer', to='transactions.customer')),
            ],
        ),
    ]
