# Generated by Django 4.2.6 on 2023-11-23 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_remove_purchaseitem_grade_remove_saleitem_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusdebthistory',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 5, 36, 59, 768418, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 5, 36, 59, 768418, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='salebill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 5, 36, 59, 784001, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='supdebthistory',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 5, 36, 59, 768418, tzinfo=datetime.timezone.utc)),
        ),
    ]
