# Generated by Django 4.2.6 on 2023-11-23 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_cusdebthistory_time_alter_purchasebill_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 5, 42, 39, 888555, tzinfo=datetime.timezone.utc)),
        ),
    ]
