# Generated by Django 4.2.6 on 2023-11-23 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_alter_purchasebill_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusdebthistory',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salebill',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='supdebthistory',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
