# Generated by Django 4.2.6 on 2023-12-01 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_alter_customer_address_alter_supplier_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
