# Generated by Django 4.2.6 on 2023-12-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_saleitem_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='condition',
            field=models.CharField(choices=[('Segar', 'Segar'), ('Tidak Segar', 'Tidak Segar')], default='Segar', max_length=18),
        ),
    ]
