# Generated by Django 4.2.6 on 2024-10-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_saleitem_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='condition',
            field=models.CharField(choices=[('Standar', 'Standar'), ('Ekonomis', 'Ekonomis')], default='Standar', max_length=18),
        ),
    ]
