# Generated by Django 4.2.6 on 2023-10-31 07:31

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
