# Generated by Django 4.2.6 on 2023-11-10 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_grade_stock_source_stock_stat_stock_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='source',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stat',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='time',
        ),
        migrations.AddField(
            model_name='stock',
            name='bad_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='good_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='grade',
            field=models.CharField(default='A', max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('stat', models.CharField(choices=[('Baik', 'Baik'), ('Busuk', 'Busuk')], default='Baik', max_length=12)),
                ('time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockitem', to='inventory.stock')),
            ],
        ),
    ]
