# Generated by Django 4.2.6 on 2023-11-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stockhistory_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
