# Generated by Django 4.2.6 on 2023-11-23 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_stockhistory_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
