# Generated by Django 4.2.6 on 2024-10-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_stockhistory_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='stat',
            field=models.CharField(choices=[('Baik', 'Baik'), ('Buruk', 'Buruk')], default='Baik', max_length=12),
        ),
    ]
